# Define services
services:

  # Database service using PostgreSQL image
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  # Backend service
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public"
    env_file:
      - .env # Load environment variables from the .env file in the current directory
