services:
  # Database service using PostgreSQL image
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  # Backend service
  backend:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      database:
        condition: service_healthy # Wait until the database is healthy
      redis:
        condition: service_started # Wait until the Redis service is started
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    env_file:
      - .env

volumes:
  redis:
    driver: local
